### ISSUE TITLE
Segmentation fault when sending message

### ISSUE THREAD

**Issue by ctramnitz** [redBorder/n2kafka#14]
I have a very simple config:

``` json
{
        "listeners": [{
                "debug": 1,
                "proto": "tcp",
                "port": 20559,
                "num_threads": 40
        }],
        "topic": "netflow",
        "rdkafka.socket.max.fails": "3",
        "rdkafka.socket.keepalive.enable": "true",
        "rdkafka.debug": "all",
        "rdkafka.partition.assignment.strategy": "roundrobin",
        "brokers": "mybroker"
}
```

but when I send a message (even just a test message using netcat) I get a segmentation fault and the error message:

`|7624898.214316|send_to_kafka:141|thr:7fff700| Can't produce message, no topic specified`

althoug the topic is specified and is also found by rdkafka:
`%7|1473854755.752|METADATA|rdkafka#producer-1| mybroker:9092/1008:   Topic #3/8: netflow with 6 partitions`

**Comment by eugpermar** [comment]
Hi @ctramnitz 
Could you please test with latest master?

**Comment by ctramnitz** [comment]
No more segfaults or topic error messages, will do some testing now, thanks!

**Comment by eugpermar** [comment]
Great! please let me know if you have any trouble :)
